In [14]:
import torch

words = open('names.txt', 'r').read().splitlines()
chars = sorted(list(set(''.join(words))))
NUM_CHARS = len(chars)+1
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0

block_size = 3
X,Y = [],[]

for w in words[:5]:
    print(w)
    context = [0] * block_size # [0,0,0] 
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context) 
        Y.append(ix)
        context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)

embeddings_dims = 2
C = torch.randn((NUM_CHARS, embeddings_dims))
print('C embedding space matrix:')
print(C[:3])

Emma
Liam
Olivia
Noah
Ava
C embedding space matrix:
tensor([[-0.8813, -1.8156],
        [ 1.6812, -0.0343],
        [ 1.6674,  0.5154]])


In [15]:



# Indexing into torch tensors with lists:
print(C[ [5,6,7] ]) # get the 5th, 6th and 7th rows of matrix C by passing in a list of indexes

# You can also pass in tensors and repeat rows to get them multiple times:
print(C[ torch.tensor([5,6,7,7,7]) ])



# indexing into C using X - see timestamp 17:39
blocks = X


print(f'X shape: {blocks.shape}') # ex 26 rows by 3 cols. Sets of the blocks of chars (inputs)
print(f'C shape: {C.shape}') # Each character in the training set has a vector coordinates set
print(f'\nC (trunc.) = {C[:2]}') # show some vector coordinates

print('\n')

print(f'block X[13] = {blocks[13]}') # [n,n,n] - 13th row showing a block of character inputs
print(f'3rd char of block X[13,2] = {blocks[13,2]}') # 13th row, 2nd dimension (3rd col), 3rd character in that block
print(f'C = {C[13]}')
print(f'Indexing into C - embedding for X[13,2] (C[X][13,2]): {C[blocks][13,2]}')

print(f'\nC[X] (trunc.) = {C[blocks][:2]}')
print(f'C[X] shape: {C[blocks].shape}') # 26 rows, each row has 3 rows in it (the block size), each of those has 2 entries (the embedding)
# [ 
#   [ # lines up with block size of 3 chars in X
#       [x,y],[x,y],[x,y] # emebeddings for each char in a block
#   ] 
# ]
# Each Row in C[X] is a set of embeddings (xy coords) for each character in the block
print('\n')
print(f'X (trunc.) = {blocks[:2]}')
print(f'C (trunc.) = {C[:2]}')

tensor([[-0.1432,  0.3760],
        [-0.1884, -1.3208],
        [ 1.8605, -0.4045]])
tensor([[-0.1432,  0.3760],
        [-0.1884, -1.3208],
        [ 1.8605, -0.4045],
        [ 1.8605, -0.4045],
        [ 1.8605, -0.4045]])
X shape: torch.Size([26, 3])
C shape: torch.Size([47, 2])

C (trunc.) = tensor([[-0.8813, -1.8156],
        [ 1.6812, -0.0343]])


block X[13] = tensor([13, 33, 30])
3rd char of block X[13,2] = 30
C = tensor([-1.3723, -0.7026])
Indexing into C - embedding for X[13,2] (C[X][13,2]): tensor([1.2261, 0.0078])

C[X] (trunc.) = tensor([[[-0.8813, -1.8156],
         [-0.8813, -1.8156],
         [-0.8813, -1.8156]],

        [[-0.8813, -1.8156],
         [-0.8813, -1.8156],
         [-0.1432,  0.3760]]])
C[X] shape: torch.Size([26, 3, 2])


X (trunc.) = tensor([[0, 0, 0],
        [0, 0, 5]])
C (trunc.) = tensor([[-0.8813, -1.8156],
        [ 1.6812, -0.0343]])


In [16]:
print(f'blocks: {blocks[:1]}')
print(f'C: {C[:1]}\n')
print(f'C[blocks]: {C[blocks][0]}') # get the first row of C three times (0,0,0 in first block of X)
# Each number in blocks is a character in that block
# the character number corresponds to a row in C (which is the coordinate embedding for that character - the row index = character number)

print('\n')

# indexing into C with X gets coordinates (a row in C) for each one of the characters in a block and puts that all into one row in the resulting Matrix
print(f'X[1] second block of char ints = {X[1]}') # block ints of chars: example: 0,0,5
print(f'embedding for first char int {X[1][0]} - C[{X[1][0]}] = {C[0]}') # coord embedding for first char in 2nd block for char int 0
print(f'embedding for second char int {X[1][1]} - C[{X[1][0]}] = {C[0]}') # coord embedding for second char in 2nd block for char int 0
print(f'embedding for third char int {X[1][2]} - C[{X[1][2]}] = {C[5]}') # coord embedding for third char in 2nd block for char int 5
print(f'\nC[X][1] = {C[X][1]}\n')

print(f'{C[X][1]}')
C[[0,0,0]]

blocks: tensor([[0, 0, 0]])
C: tensor([[-0.8813, -1.8156]])

C[blocks]: tensor([[-0.8813, -1.8156],
        [-0.8813, -1.8156],
        [-0.8813, -1.8156]])


X[1] second block of char ints = tensor([0, 0, 5])
embedding for first char int 0 - C[0] = tensor([-0.8813, -1.8156])
embedding for second char int 0 - C[0] = tensor([-0.8813, -1.8156])
embedding for third char int 5 - C[5] = tensor([-0.1432,  0.3760])

C[X][1] = tensor([[-0.8813, -1.8156],
        [-0.8813, -1.8156],
        [-0.1432,  0.3760]])

tensor([[-0.8813, -1.8156],
        [-0.8813, -1.8156],
        [-0.1432,  0.3760]])


tensor([[-0.8813, -1.8156],
        [-0.8813, -1.8156],
        [-0.8813, -1.8156]])

In [17]:

############################################################################################################################################################ 
#  indexing into C with X gets coordinates (a row in C) for each one of the characters in a block and puts that all into one row in the resulting Matrix 
# ###########################################################################################################################################################
# print(f'C[X] = {C[X]}') # X is a list of blocks
print(X[:2])
C[[0,0,5]] # example - the second block of X is a list so we index into C with that to get coordinates for each char in the block (the index of C lines up with coordinates for the char int representation)

XX = X[:2]
print(XX)

print(C[XX])

C[torch.tensor([[0, 0, 0],
        [0, 0, 5]])]

tensor([[0, 0, 0],
        [0, 0, 5]])
tensor([[0, 0, 0],
        [0, 0, 5]])
tensor([[[-0.8813, -1.8156],
         [-0.8813, -1.8156],
         [-0.8813, -1.8156]],

        [[-0.8813, -1.8156],
         [-0.8813, -1.8156],
         [-0.1432,  0.3760]]])


tensor([[[-0.8813, -1.8156],
         [-0.8813, -1.8156],
         [-0.8813, -1.8156]],

        [[-0.8813, -1.8156],
         [-0.8813, -1.8156],
         [-0.1432,  0.3760]]])